# Generated by Django 5.1.6 on 2025-03-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phan_loai_khoi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoa', models.CharField(max_length=200)),
                ('khoi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nhan_vien.khoi')),
            ],
        ),
        migrations.CreateModel(
            name='Nhan_vien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhan_vien', models.CharField(max_length=300)),
                ('ma_nhan_vien', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mat_khau', models.CharField(blank=True, max_length=250, null=True)),
                ('hinh_anh', models.ImageField(blank=True, default='images/products.default.png', null=True, upload_to='images/products')),
                ('khoa_NV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nhan_vien.khoa')),
            ],
        ),
    ]
