# Generated by Django 5.1.6 on 2025-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nhan_vien', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhan_vien',
            name='hinh_anh',
            field=models.ImageField(blank=True, default='images/staffs.nv1.jpg', null=True, upload_to='images/staffs'),
        ),
    ]
