# Generated by Django 5.1.6 on 2025-03-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nhan_vien', '0002_alter_nhan_vien_hinh_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhan_vien',
            name='hinh_anh',
            field=models.ImageField(blank=True, default='nv1.jpg', null=True, upload_to=''),
        ),
    ]
