# Generated by Django 5.1.6 on 2025-02-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoi_khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoi', models.CharField(max_length=200)),
                ('khoa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nhan_vien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhan_vien', models.CharField(max_length=300)),
                ('ma_nhan_vien', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('hinh_anh', models.ImageField(default='images/products.default.png', upload_to='images/products')),
                ('khoa_NV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.khoi_khoa')),
            ],
        ),
        migrations.CreateModel(
            name='Quy_trinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STT_QT', models.CharField(max_length=300)),
                ('So_hieu_QTKT', models.CharField(max_length=300)),
                ('So_quyet_dinh', models.CharField(max_length=300)),
                ('Ten_quy_trinh', models.TextField(max_length=300)),
                ('So_buoc', models.CharField(max_length=30)),
                ('khoa_QT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.khoi_khoa')),
            ],
        ),
        migrations.CreateModel(
            name='Buoc_quy_trinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_buoc_QT', models.CharField(max_length=50)),
                ('Noi_dung_buoc', models.TextField(max_length=300)),
                ('Chi_so_an_toan', models.CharField(max_length=1)),
                ('Ten_quy_trinh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.quy_trinh')),
            ],
        ),
    ]
