# Generated by Django 5.1.6 on 2025-02-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Giam_sat_quy_trinh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhan_vien',
            name='hinh_anh',
            field=models.ImageField(blank=True, default='images/products.default.png', null=True, upload_to='images/products'),
        ),
    ]
