# Generated by Django 5.1.6 on 2025-03-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Giam_sat_quy_trinh', '0002_alter_nhan_vien_hinh_anh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quy_trinh_giam_sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nhan_vien_duoc_giam_sat', models.CharField(max_length=300)),
                ('Kq_gs', models.TextField(max_length=9999)),
                ('Ngay_giam_sat', models.DateTimeField(auto_now_add=True)),
                ('Nhan_vien_giam_sat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.nhan_vien')),
                ('Ten_quy_trinh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.quy_trinh')),
            ],
            options={
                'ordering': ('-Ngay_giam_sat',),
            },
        ),
    ]
