# Generated by Django 5.1.6 on 2025-03-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Giam_sat_quy_trinh', '0003_quy_trinh_giam_sat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khoa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Khoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phan_loai_khoi', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='nhan_vien',
            name='khoa_NV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.khoa'),
        ),
        migrations.AlterField(
            model_name='quy_trinh',
            name='khoa_QT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.khoa'),
        ),
        migrations.AddField(
            model_name='khoa',
            name='khoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.khoi'),
        ),
        migrations.DeleteModel(
            name='Khoi_khoa',
        ),
    ]
