# Generated by Django 5.1.6 on 2025-03-06 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Giam_sat_quy_trinh', '0004_khoa_khoi_alter_nhan_vien_khoa_nv_and_more'),
        ('Nhan_vien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khoa',
            name='khoi',
        ),
        migrations.AlterField(
            model_name='quy_trinh',
            name='khoa_QT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nhan_vien.khoa'),
        ),
        migrations.RemoveField(
            model_name='nhan_vien',
            name='khoa_NV',
        ),
        migrations.AlterField(
            model_name='quy_trinh_giam_sat',
            name='Nhan_vien_giam_sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nhan_vien.nhan_vien'),
        ),
        migrations.DeleteModel(
            name='Khoi',
        ),
        migrations.DeleteModel(
            name='Khoa',
        ),
        migrations.DeleteModel(
            name='Nhan_vien',
        ),
    ]
