# Generated by Django 5.1.6 on 2025-03-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Giam_sat_quy_trinh', '0005_remove_khoa_khoi_alter_quy_trinh_khoa_qt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quy_trinh',
            name='khoa_QT',
        ),
        migrations.RemoveField(
            model_name='quy_trinh_giam_sat',
            name='Ten_quy_trinh',
        ),
        migrations.RemoveField(
            model_name='quy_trinh_giam_sat',
            name='Nhan_vien_giam_sat',
        ),
        migrations.DeleteModel(
            name='Buoc_quy_trinh',
        ),
        migrations.DeleteModel(
            name='Quy_trinh',
        ),
        migrations.DeleteModel(
            name='Quy_trinh_giam_sat',
        ),
    ]
