# Generated by Django 5.1.6 on 2025-03-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Giam_sat_quy_trinh', '0006_remove_quy_trinh_khoa_qt_and_more'),
        ('Nhan_vien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quy_trinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STT_QT', models.CharField(max_length=300)),
                ('So_hieu_QTKT', models.CharField(max_length=300)),
                ('So_quyet_dinh', models.CharField(max_length=300)),
                ('Ten_quy_trinh', models.TextField(max_length=300)),
                ('So_buoc', models.CharField(max_length=30)),
                ('khoa_QT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nhan_vien.khoa')),
            ],
        ),
        migrations.CreateModel(
            name='Buoc_quy_trinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ma_buoc_QT', models.CharField(max_length=50)),
                ('Noi_dung_buoc', models.TextField(max_length=300)),
                ('Chi_so_an_toan', models.CharField(max_length=1)),
                ('Ten_quy_trinh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.quy_trinh')),
            ],
        ),
        migrations.CreateModel(
            name='Quy_trinh_giam_sat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nhan_vien_duoc_giam_sat', models.CharField(max_length=300)),
                ('Kq_gs', models.TextField(max_length=9999)),
                ('Ngay_giam_sat', models.DateTimeField(auto_now_add=True)),
                ('Nhan_vien_giam_sat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nhan_vien.nhan_vien')),
                ('Ten_quy_trinh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Giam_sat_quy_trinh.quy_trinh')),
            ],
            options={
                'ordering': ('-Ngay_giam_sat',),
            },
        ),
    ]
