# Generated by Django 5.1.6 on 2025-03-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Giam_sat_quy_trinh', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buoc_quy_trinh',
            name='Chi_so_an_toan',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
