# Generated by Django 5.1.6 on 2025-03-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Giam_sat_quy_trinh', '0008_alter_buoc_quy_trinh_chi_so_an_toan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quy_trinh_giam_sat',
            old_name='Nhan_vien_duoc_giam_sat',
            new_name='ID_Nhan_vien_duoc_giam_sat',
        ),
    ]
